name: 'pgs-action'
description: 'Github Action to publish static site to pgs.sh'
author: 'picosh'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  user:
    description: 'SSH username'
    required: true
  key:
    description: 'Private key'
    required: true
  src:
    description: 'Recursive files to deploy'
    required: true
  project:
    description: 'Project to deploy'
    required: true
  promote:
    description: 'Promote project to this deployment'
    required: false
  retain:
    description: 'Removes all projects except the latest (N) updated projects that match prefix'
    required: false
  retain_num:
    description: 'The latest updated number of projects to keep'
    required: false
    default: 3
runs:
  using: 'composite'
  steps:
    - name: check runner os
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::Support Linux Only"
        exit 1
    - name: setup private key
      shell: bash
      run: |
        echo -e "${{ inputs.key }}" >__TEMP_INPUT_KEY_FILE
        chmod 600 __TEMP_INPUT_KEY_FILE
    - name: upload to pgs
      shell: bash
      run: |
        rsync -rv \
          -e "ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE" \
          "${{ inputs.src }}" \
          "${{ inputs.user }}"@pgs.sh:/"${{ inputs.project }}"
    - name: link project
      if: ${{ inputs.promote != '' }}
      shell: bash
      run: |
        ssh -v \
          -o IdentitiesOnly=yes \
          -o StrictHostKeyChecking=no \
          -i __TEMP_INPUT_KEY_FILE \
          "${{ inputs.user }}"@pgs.sh \
          link "${{ inputs.promote }}" --to "${{ inputs.project }}" --write
    - name: retain projects
      if: ${{ inputs.retain != '' }}
      shell: bash
      run: |
        ssh -v \
          -o IdentitiesOnly=yes \
          -o StrictHostKeyChecking=no \
          -i __TEMP_INPUT_KEY_FILE \
          "${{ inputs.user }}"@pgs.sh retain "${{ inputs.retain }}" -n "${{inputs.retain_num}}" --write
    - name: remove private key
      shell: bash
      run: |
        rm __TEMP_INPUT_KEY_FILE
